# Generated by Django 6.0.6 on 2026-06-26 06:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_code', models.CharField(max_length=16)),
                ('bank_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=128)),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_ref', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(choices=[('card', 'Card'), ('transfer', 'Bank Transfer')], default='card', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('transferred', 'Transferred to Dev')], default='pending', max_length=16)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('nomba_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='checkout.dev')),
            ],
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('merchant_tx_ref', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=16)),
                ('nomba_response', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_logs', to='checkout.dev')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_log', to='checkout.payment')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualAccountSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=128)),
                ('account_ref', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting Payment'), ('received', 'Payment Received'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_account', to='checkout.payment')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('card_token', models.TextField()),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_type', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to='checkout.dev')),
            ],
            options={
                'unique_together': {('dev', 'customer_email')},
            },
        ),
    ]
