# Generated by Django 5.0.6 on 2026-06-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('transferred', 'Transferred to Dev'), ('refunded', 'Refunded to Customer')], default='pending', max_length=16),
        ),
    ]
