# Generated by Django 5.0.6 on 2026-07-02 12:08

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0002_alter_payment_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savedcard",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="transferlog",
            name="dev",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="dev",
        ),
        migrations.RemoveField(
            model_name="savedcard",
            name="dev",
        ),
        migrations.AddField(
            model_name="payment",
            name="dev_id",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="savedcard",
            name="dev_id",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="transferlog",
            name="dev_id",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name="savedcard",
            unique_together={("dev_id", "customer_email")},
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_ref",
            field=models.CharField(
                default=checkout.models.generate_reference,
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="Dev",
        ),
    ]
