# Generated by Django 5.0.6 on 2026-07-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_transferlog_dev_remove_payment_dev_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferlog',
            name='dev_id',
        ),
    ]
